# Data preprocessing


## Data loading

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
!gdown --id 1xkS3QLAFrzTfJqc6qs24k9ey6sk3aSNe

Downloading...
From: https://drive.google.com/uc?id=1xkS3QLAFrzTfJqc6qs24k9ey6sk3aSNe
To: /content/bank_train.csv
100% 2.33M/2.33M [00:00<00:00, 73.1MB/s]


In [ ]:
bankdata = pd.read_csv('bank_train.csv')

## Data exploring

In [ ]:
bankdata.head()

age         job   marital  education  ... pdays  previous poutcome subscribed
0   29      admin.   married  secondary  ...    -1         0  unknown         no
1   33      admin.    single   tertiary  ...    -1         0  unknown         no
2   30  management   married   tertiary  ...    -1         0  unknown         no
3   33      admin.  divorced  secondary  ...    -1         0  unknown        yes
4   42  technician   married   tertiary  ...    -1         0  unknown         no

[5 rows x 16 columns]

In [ ]:
bankdata.dtypes

age            int64
job           object
marital       object
education     object
default       object
balance        int64
housing       object
loan          object
contact       object
day            int64
month         object
campaign       int64
pdays          int64
previous       int64
poutcome      object
subscribed    object
dtype: object

In [ ]:
bankdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29387 entries, 0 to 29386
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         29387 non-null  int64 
 1   job         29387 non-null  object
 2   marital     29387 non-null  object
 3   education   29387 non-null  object
 4   default     29387 non-null  object
 5   balance     29387 non-null  int64 
 6   housing     29387 non-null  object
 7   loan        29387 non-null  object
 8   contact     29387 non-null  object
 9   day         29387 non-null  int64 
 10  month       29387 non-null  object
 11  campaign    29387 non-null  int64 
 12  pdays       29387 non-null  int64 
 13  previous    29387 non-null  int64 
 14  poutcome    29387 non-null  object
 15  subscribed  29387 non-null  object
dtypes: int64(6), object(10)
memory usage: 3.6+ MB


In [ ]:
df_nunique = {var: pd.DataFrame(bankdata[var].value_counts()) 
              for var in {'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'subscribed'}}


In [ ]:
from IPython.core.display import HTML

def multi_table(table_list):
    ''' Acceps a list of IpyTable objects and returns a table which contains each IpyTable in a cell
    '''
    return HTML(
        '<table><tr style="background-color:white;">' + 
        ''.join(['<td>' + table._repr_html_() + '</td>' for table in table_list]) +
        '</tr></table>')

multi_table([df_nunique['job'], df_nunique['marital'],df_nunique['education']
            ,df_nunique['default'],df_nunique['housing'],df_nunique['loan'],df_nunique['contact'],df_nunique['month'],
             df_nunique['poutcome'],df_nunique['subscribed']])

## Split X and y

In [ ]:
bankdata

age          job   marital  ... previous poutcome  subscribed
0       29       admin.   married  ...        0  unknown          no
1       33       admin.    single  ...        0  unknown          no
2       30   management   married  ...        0  unknown          no
3       33       admin.  divorced  ...        0  unknown         yes
4       42   technician   married  ...        0  unknown          no
...    ...          ...       ...  ...      ...      ...         ...
29382   55    housemaid  divorced  ...        0  unknown          no
29383   38  blue-collar   married  ...        0  unknown          no
29384   52   management   married  ...        0  unknown          no
29385   34   technician    single  ...        0  unknown          no
29386   44   management   married  ...        0  unknown          no

[29387 rows x 16 columns]

In [ ]:
bankdata.subscribed[bankdata.subscribed == 'no'] = int(0)
bankdata.subscribed[bankdata.subscribed == 'yes'] = int(1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
bankdata

age          job   marital  ... previous poutcome  subscribed
0       29       admin.   married  ...        0  unknown           0
1       33       admin.    single  ...        0  unknown           0
2       30   management   married  ...        0  unknown           0
3       33       admin.  divorced  ...        0  unknown           1
4       42   technician   married  ...        0  unknown           0
...    ...          ...       ...  ...      ...      ...         ...
29382   55    housemaid  divorced  ...        0  unknown           0
29383   38  blue-collar   married  ...        0  unknown           0
29384   52   management   married  ...        0  unknown           0
29385   34   technician    single  ...        0  unknown           0
29386   44   management   married  ...        0  unknown           0

[29387 rows x 16 columns]

In [ ]:
X = bankdata.iloc[:, :-1]
y = bankdata.iloc[:, -1]

In [ ]:
X

age          job   marital  ... pdays previous  poutcome
0       29       admin.   married  ...    -1        0   unknown
1       33       admin.    single  ...    -1        0   unknown
2       30   management   married  ...    -1        0   unknown
3       33       admin.  divorced  ...    -1        0   unknown
4       42   technician   married  ...    -1        0   unknown
...    ...          ...       ...  ...   ...      ...       ...
29382   55    housemaid  divorced  ...    -1        0   unknown
29383   38  blue-collar   married  ...    -1        0   unknown
29384   52   management   married  ...    -1        0   unknown
29385   34   technician    single  ...    -1        0   unknown
29386   44   management   married  ...    -1        0   unknown

[29387 rows x 15 columns]

In [ ]:
y=y.astype(int)

In [ ]:
y

0        0
1        0
2        0
3        1
4        0
        ..
29382    0
29383    0
29384    0
29385    0
29386    0
Name: subscribed, Length: 29387, dtype: int64

## Feature engineering

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3, 4, 6, 7, 8, 10, 14])], remainder='passthrough')
X_encoded = np.array(ct.fit_transform(X))
print(X_encoded)

[[ 1.  0.  0. ...  1. -1.  0.]
 [ 1.  0.  0. ...  3. -1.  0.]
 [ 0.  0.  0. ...  1. -1.  0.]
 ...
 [ 0.  0.  0. ...  1. -1.  0.]
 [ 0.  0.  0. ...  1. -1.  0.]
 [ 0.  0.  0. ...  1. -1.  0.]]


In [ ]:
X_encoded[0]

array([ 1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  2.900e+01,
        1.489e+03,  2.000e+01,  1.000e+00, -1.000e+00,  0.000e+00])

# Model training

## Train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size = 0.2, random_state = 88)

In [ ]:
y_train

15541    0
21021    0
17130    0
7371     0
27250    0
        ..
24938    0
2481     0
4047     0
6432     0
26584    0
Name: subscribed, Length: 23509, dtype: int64

In [ ]:
models = {
    'Logic Regression': LogisticRegression(),
    'KNN': KNeighborsClassifier(),
    'Random Forest': RandomForestClassifier()
}

def fit_and_score(models, X_train, y_train, X_test, y_test):
  np.random.seed(random_state)
  model_scores = {}
  for name, model in models.items():
    model.fit(X_train, y_train)
    model_scores[name] = model.score(X_test, y_test)
  return model_scores

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

In [ ]:
score = model.score(X_test, y_test)
score

0.8812521265736645

# with cross validation

In [ ]:
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score

In [ ]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
model = LogisticRegression()

In [ ]:
scores = cross_val_score(model, X_encoded, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [ ]:
scores

array([0.88907792, 0.88431439, 0.87853011, 0.88363389, 0.87342634,
       0.88533515, 0.8863559 , 0.88699796, 0.88291355, 0.89652825,
       0.89009867, 0.88669616, 0.88533515, 0.8856754 , 0.88431439,
       0.88261313, 0.87138482, 0.88053097, 0.89652825, 0.88121171,
       0.87172508, 0.87682885, 0.8856754 , 0.87853011, 0.88295339,
       0.89418169, 0.89452195, 0.88563649, 0.89380531, 0.88155208])

# NN

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
X_train.shape

(23509, 50)

In [ ]:
model = Sequential()
model.add(Dense(12, input_shape=(23509,50), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
2351/2351 [==============================] - 4s 1ms/step - loss: 0.6416 - accuracy: 0.8606
Epoch 2/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.4888 - accuracy: 0.8728
Epoch 3/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.4611 - accuracy: 0.8722
Epoch 4/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.4247 - accuracy: 0.8738
Epoch 5/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.3972 - accuracy: 0.8769
Epoch 6/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.3928 - accuracy: 0.8787
Epoch 7/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.3762 - accuracy: 0.8796
Epoch 8/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.3596 - accuracy: 0.8826
Epoch 9/150
2351/2351 [==============================] - 3s 1ms/step - loss: 0.3470 - accuracy: 0.8843
Epoch 10/150
2351/2351 [==============================] - 3s 1ms/step - l

In [ ]:
testing_y = model.predict(testing_encoded)

In [ ]:
testing_y

array([[0.03107682],
       [0.12334281],
       [0.04079005],
       ...,
       [0.02464932],
       [0.0735369 ],
       [0.01899436]], dtype=float32)

In [ ]:
predicted = np.argmax(testing_y, axis = 1)

In [ ]:
predicted

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
pd.Series(predicted)

0        0
1        0
2        0
3        0
4        0
        ..
15819    0
15820    0
15821    0
15822    0
15823    0
Length: 15824, dtype: int64

In [ ]:
testing_idx['subscribed'] = pd.Series(predicted)

In [ ]:
testing_idx

In [ ]:
testing_idx.to_csv('predicted.csv', index=False)

In [ ]:
!gdown --id 1YcwuCLoI9qGfHwWNTPL3hfLlx6SEid5Q

Downloading...
From: https://drive.google.com/uc?id=1YcwuCLoI9qGfHwWNTPL3hfLlx6SEid5Q
To: /content/bank_test.csv
100% 1.29M/1.29M [00:00<00:00, 83.2MB/s]


In [ ]:
testing = pd.read_csv('bank_test.csv')

In [ ]:
testing

In [ ]:
testing_X = testing.iloc[:, 1:]
testing_idx = testing.iloc[:, :1]

In [ ]:
testing_idx

id
0          0
1          1
2          2
3          3
4          4
...      ...
15819  15819
15820  15820
15821  15821
15822  15822
15823  15823

[15824 rows x 1 columns]

In [ ]:
testing_encoded = np.array(ct.fit_transform(testing_X))

In [ ]:
testing_encoded

In [ ]:
testing_y = model.predict(testing_encoded)

In [ ]:
pd.Series(testing_y)

0        0
1        0
2        0
3        0
4        0
        ..
15819    0
15820    0
15821    0
15822    0
15823    0
Length: 15824, dtype: int64

In [ ]:
testing_idx['subscribed'] = pd.Series(testing_y)

In [ ]:
testing_idx

id  subscribed
0          0           0
1          1           0
2          2           0
3          3           0
4          4           0
...      ...         ...
15819  15819           0
15820  15820           0
15821  15821           0
15822  15822           0
15823  15823           0

[15824 rows x 2 columns]

In [ ]:
testing_idx.to_csv('predicted.csv', index=False)